### ISSUE TITLE
[Improve]: Flutterのコンテンツが表示されるまでの数秒間白い画面が表示される。

### ISSUE THREAD

**Issue by a-skua** [FlutterKaigi/2023#125]
### Describe

読み込んで最初に数秒間白いページが表示されるのが少々気になります。
FlutterKaigi 2023のテーマカラーやロゴの表示を検討しても良いかもしれないです。

### Screenshots

Web Embeddedの活用でこう言った制御ができるようになっています。
![Screen Recording 2023-08-02 at 0 17 11](https://github.com/FlutterKaigi/2023/assets/41745521/e1a9d4d5-e539-40f7-b4fd-d32989afaf96)

1. HTMLコンテンツの表示(この時Flutterを描画する要素は `opacity: 0`)
2. Flutterコンテンツが読み込み終わったことをJSに通知
3. JSが`opacity: 1`に変更する

### Environment

- Device: all
- OS: all
- Browser: all
- Version: all
- Commit SHA: -

### Additional context

上記サンプル、こちらに置いているのでよければ参考に。
https://a-skua.github.io/example-flutter-web/

**Comment by blendthink** [comment]
Issue 作成ありがとうございます！
まずはデザイン調整進めさせていただきます 🙏

**Comment by blendthink** [comment]
デザイナーさんと相談して、描画に１〜３秒程度かかっているため [Circular progress indicator](https://m3.material.io/components/progress-indicators/overview#a643e259-b032-49ea-96a6-efdac1e0725b) で対応することになりました 🙆‍♂️ 

カラーは↓でお願いします！

- Progress Bar: primary: Color(0xFFD0BCFF)
- 背景色: onSecondaryContainer: Color(0xFF1D192B)

**Comment by a-skua** [comment]
こちら着手します〜
