### ISSUE TITLE
[Bug]: Padding in staff and footer sections not properly set

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2023#139]
### Describe the bug

Padding of staff and footer sections not set as designed.

Design: https://www.figma.com/file/LsVB4KlIMXD4Z1FfB8KyuU/FlutterKaigi-Web-2023?node-id=95%3A834&mode=dev

### Screenshots

![image](https://github.com/FlutterKaigi/2023/assets/32213113/43fd3c2c-a6db-444e-aaf4-9b56ea71df8f)

### To Reproduce

1. Go to https://flutterkaigi.jp/2023/
2. Scroll down to the bottom

### Expected behavior

Leave 200px between the staff section and the footer section.

![image](https://github.com/FlutterKaigi/2023/assets/32213113/e6f78ff9-061b-456e-9637-24e316070e99)

### Environment

- Commit SHA: 30ea7c5f467cd8113a2e9927b1b3e230410ba970

**Comment by yoshimuratakuma0** [comment]
:raising_hand:
