### ISSUE TITLE
[Bug]: Safariで開いたときにスクロールできない

### ISSUE THREAD

**Issue by anishi-pfr** [FlutterKaigi/2023#218]
### Describe the bug

以下の動画のようにSafariで下スクロールをしようとするとできないです。またスクロールを試み続けると途中でロード画面が表示されます。

### Screenshots

<video src="https://github.com/FlutterKaigi/2023/assets/117054814/d1317840-bf73-4288-8199-aa9245042dac" width="320" />

### To Reproduce

1. Go to https://flutterkaigi.jp/2023/
2. Scroll down to bottom

### Expected behavior

最後までスクロールできる

### Environment

- iPhone13 pro
- iOS 17.0.3
- Safari
- Version・commit hash。その他の画面も見れなかったので確認できませんでした。

**Comment by blendthink** [comment]
@anishi-pfr 
開発メンバーの端末では発生せず、、
もしかすると端末スペックや OS のバージョンによる問題か、Safari のバージョンによる問題かもしれませんので、お手数ですがそれらのバージョンを教えていただくことは可能でしょうか？

**Comment by anishi-pfr** [comment]
すみません、スペック等書くのを忘れてしまいした。（バグレポートから上げたときに書いたスペック等が消滅してしまったかもしれないです🙏）
ちなみに今日再度試したところスクロールできました！なので一旦closeしておきます。もしかしたらネットワークの問題で何かしらのアセットがロードできていなかったのかもしれないです。

一応環境はこちらです。
- OS: iOS 17.0.3
- iPhone 13 Pro
- Safari：（ぱっと確認できなかったのでバグ再発したら調べます！）
