### ISSUE TITLE
[Bug]: フッターのContactがリンク切れ

### ISSUE THREAD

**Issue by ENDOTAKUMI** [FlutterKaigi/2023#98]
### Describe the bug

こちらURLが間違っているようです。

> リクエストされたファイルは存在しません。
URL が間違っておらず、ファイルが存在することをご確認ください。

### Screenshots

<img src="https://github.com/FlutterKaigi/2023/assets/33868170/fe147543-ba47-484b-9b74-05ae0fb5a341" width="320" />

### To Reproduce

1. フッターのContactをクリックする

### Expected behavior

リンクを修正する

### Environment

- Commit SHA: [6093d1da3efe6836cb826a63d07058728445e4b1]

**Comment by YumNumm** [comment]
@ENDOTAKUMI Issue作成ありがとうございます! 
https://github.com/FlutterKaigi/2023/pull/102 こちらで対応させていただきました!
